sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - latexmk
install:
  - make book
