sudo: false
language: python
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk
install:
  - make book
