sudo: false
language: python
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - latexmk
install:
  - make book
