sudo: false
language: python
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk
script:
  - make book
deploy:
     provider: releases
     api_key:
         secure: 48e5dd6e1f36586580a2ee9e15404c090386e46b
     file:
         - se4ml.pdf
     skip_cleanup: true
     on:
         tags: true
